### ISSUE TITLE
kirkstone-2.2.0-yocto-r1.1 build broken

### ISSUE THREAD

**Issue by koansoftware** [compulab-yokneam/meta-bsp-imx9#2]
The **meta-bsp-imx9** version **kirkstone-2.2.0-yocto-r1.1** is broken

In this case using [kirkstone-2.2.0-yocto-r1.1](https://github.com/compulab-yokneam/meta-bsp-imx9/blob/kirkstone-2.2.0-yocto-r1.1/README.md) setup instructions there is an error

WARNING: linux-compulab-6.1.1-r0 do_fetch: Failed to fetch URL file://0001-ucm-imx93-dts-fix-lvds-touch-screen.patch, attempting MIRRORS if available
ERROR: linux-compulab-6.1.1-r0 do_fetch: Fetcher failure: Unable to find file file://0001-ucm-imx93-dts-fix-lvds-touch-screen.patch anywhere. The paths that were searched were...

**Comment by vraevsky** [comment]
https://github.com/compulab-yokneam/meta-bsp-imx9/commit/dd10a9c07dbee2ccc63022c892ff8c427327e01e

**Comment by yaakovEntin** [comment]
revised the fix, use TOT
