### ISSUE TITLE
kirkstone-2.2.0-yocto build broken

### ISSUE THREAD

**Issue by koansoftware** [compulab-yokneam/meta-bsp-imx9#3]
The meta-bsp-imx9 version **kirkstone-2.2.0-yocto** (default) is broken

In this case following the  [README.md](https://github.com/compulab-yokneam/meta-bsp-imx9/blob/kirkstone-2.2.0/README.md) setup instructions there is an error.

You forgot to manage the ucm-imx93-lvds.dtb in [ucm-imx93.conf](https://github.com/compulab-yokneam/meta-bsp-imx9/blob/kirkstone-2.2.0/conf/machine/ucm-imx93.conf) as expected by the new kernel commits you did.

```
| make[2]: *** No rule to make target 'arch/arm64/boot/dts/compulab/ucm-imx93-lvds.dtb'.  Stop.
| make[1]: *** [/home/works/yocto-compulab-kirkstone/build-ucm-imx93/tmp/work-shared/ucm-imx93/kernel-source/scripts/Makefile.build:500: arch/arm64/boot/dts/compulab] Error 2
| make: *** [/home/works/yocto-compulab-kirkstone/build-ucm-imx93/tmp/work-shared/ucm-imx93/kernel-source/Makefile:1471: compulab/ucm-imx93-lvds.dtb] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/works/yocto-compulab-kirkstone/sources/meta-bsp-imx9/recipes-kernel/linux/linux-compulab_6.1.1.bb:do_compile) failed with exit code '1'
```

**Comment by vraevsky** [comment]
https://github.com/compulab-yokneam/meta-bsp-imx9/commit/59f44dd58aeaae9798f18ad1a5c6f54394ccd740
